#!/bin/bash
# fdf-help.sh - Help and documentation for Fuzzy Drunk Finder
# This module provides the help text and usage information

# Function for fuzzy directory navigation help
fdf_help() {
    echo "Fuzzy Drunk Finder v$FDF_VERSION - Interactive Directory Navigation Tool"
    echo ""
    echo "DESCRIPTION:"
    echo "  A powerful tool for quickly navigating directories using fuzzy search."
    echo "  It allows for rapid directory discovery and navigation with history tracking."
    echo ""
    echo "USAGE:"
    echo "  fdf [options] [directory]"
    echo ""
    echo "OPTIONS:"
    echo "  --hidden      Include hidden directories in search"
    echo "  --depth N     Set maximum directory depth for searches (default: $DEFAULT_DEPTH)"
    echo "  --unlimited   Remove depth limit for searches (may be slow in large directories)"
    echo "  --no-history  Don't use or update the directory history"
    echo "  --debug       Enable debug mode with detailed information"
    echo "  --rebuild-cache  Force rebuild of cache for this search"
    echo "  --version     Display version information"
    echo "  --search      Test mode: show what would be searched (optional: provide search term)"
    echo "  directory     Starting directory (default: current directory)"
    echo ""
    echo "COMMANDS:"
    echo "  fdf            Run interactive fuzzy finder in current directory"
    echo "  fdf_help       Display this help message"
    echo "  fdf_clear_cache Clear the cache directory"
    echo "  fdf_clear_history Clear the history file (prompts for confirmation)"
    echo "  fdf_config     Edit the user configuration file"
    echo ""
    echo "EXAMPLES:"
    echo "  fdf                  # Navigate from current directory"
    echo "  fdf ~/Documents      # Navigate starting from ~/Documents"
    echo "  fdf --hidden         # Include hidden directories"
    echo "  fdf --depth 5        # Search deeper into directory tree"
    echo "  fdf --unlimited      # No depth restriction (may be slow)"
    echo "  fdf --search projects # Test what would match 'projects'"
    echo ""
    echo "CONFIGURATION:"
    echo "  User config:    $USER_CONFIG_FILE"
    echo "  Cache directory: $CACHE_DIR"
    echo "  History file:    $HISTORY_FILE"
    echo ""
    echo "To create/edit config: fdf_config"
}
